# Generated by Django 4.1.5 on 2023-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y%m%d')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0)),
                ('devtool', models.CharField(choices=[('django', 'Django'), ('react', 'React'), ('spring', 'Spring'), ('node.js', 'Node.js'), ('java', 'Java'), ('c++', 'C++')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ToolList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
    ]
