# Generated by Django 4.1.5 on 2023-01-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='yearsMv',
            field=models.CharField(help_text='개봉 년도', max_length=32),
        ),
    ]
